[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
kingpepe_bridge = "EfoRF4BDDspsi53XYL62mCyhCtf3FceV5LpRkRdwYqKM"
kingpepe_transceiver = "AkqLGFTy43D9cLjHRTQGpRGb2uWA8nuVyGb2bJYHKCrN"

[workspace]
types = "modules"
