[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
kingpepe_bridge = "Gm4g..."  # placeholder; set by deployment tooling
kingpepe_transceiver = "H2g4..."

[workspace]
types = "modules"

