[package]
name = "frost_runtime"
version = "0.1.0"
edition = "2021"
publish = false
license-file = "../../LICENSE"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.10.9"
rand_core = { version = "0.6.4", features = ["getrandom"] }
thiserror = "1.0.69"

[dev-dependencies]
serde_json = "1.0.151"
