[package]
name = "kingpepe-bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "kingpepe_bridge"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
bridge-messages = { path = "../../modules/bridge-messages" }
kingpepe-transceiver = { path = "../kingpepe-transceiver", features = ["no-entrypoint"] }
solana-program = "=1.18.26"
thiserror = "1.0.69"
zeroize_derive = "=1.4.2"
