// DISPLAY ONLY. The only request is GET to the fixed public market endpoint.
import {MARKET,FRESHNESS} from './market-identities.js';
import {validateMarket,displayHealth,formatMarket as f,chartSeries,PRICE_LABELS,TIMEFRAMES,overviewMetrics} from './market-display-model.js?v=fullwidth-v1';
const explorer=(kind,id)=>'https://explorer.solana.com/'+kind+'/'+id;
const short=id=>id.slice(0,6)+'…'+id.slice(-6);
export function renderMarketDisplay(host){
  const root=document.createElement('section');root.className='market-display';root.setAttribute('aria-label','KingPepe live market display');root.dataset.mode='DISPLAY_ONLY';
  root.innerHTML=`
    <header class="market-header"><div class="market-brand"><img src="/kingpepe-logo.jpg" alt="" width="48" height="48"><div><p class="market-eyebrow">KINGPEPE LIVE MARKET</p><h1>KPEPE <span>/ SOL</span></h1></div></div><div class="market-health" data-health="UNAVAILABLE" role="status"><span aria-hidden="true"></span><b data-market="health">CONNECTING</b></div></header>
    <div class="market-intro"><span>Raydium CLMM · Live market display</span><span>Solana Mainnet · Read only</span></div>
    <div class="market-dashboard">
    <section class="market-card market-price-card" aria-label="Market price">
      <div><p class="market-eyebrow" data-market="price-label">PRICE UNAVAILABLE</p><p class="market-price"><span class="market-unit">1 KPEPE =</span><strong data-market="price">—</strong><span class="market-price-unit">SOL</span></p><p class="market-usd" data-market="usd">$ —</p></div>
      <div class="market-price-context"><span class="market-small">Price observed</span><time data-market="price-time">—</time><span class="market-small" data-market="price-context">Waiting for verified market data</span></div>
    </section>
    <section class="market-card market-chart-card" aria-labelledby="market-chart-title"><div class="market-section-head"><div><h2 id="market-chart-title">Price history</h2><p class="market-small" data-market="chart-caption">Raydium finalized swaps · SOL per KPEPE</p></div><div class="market-timeframes" role="group" aria-label="Chart timeframe">${Object.keys(TIMEFRAMES).map(x=>`<button type="button" data-frame="${x}" aria-pressed="${x==='ALL'}" disabled>${x}</button>`).join('')}</div></div><div class="market-chart" data-market="chart"><div class="market-empty"><span class="market-empty-glyph" aria-hidden="true">⌁</span><strong>Insufficient trading history</strong><p>Only verified, finalized trades appear here.</p></div></div><p class="market-small" data-market="chart-summary">No synthetic candles, prices or volume.</p></section>
    <div class="market-stats-group">
    <section class="market-overview" aria-label="USD market overview">${[['cap','Mkt Cap','Solana supply · estimate'],['liquidity','Liquidity','Raydium reported TVL'],['usd','Price USD','Displayed price conversion']].map(([id,label,basis])=>`<div class="market-card market-stat"><span>${label}</span><strong data-market="overview-${id}">—</strong><small>${basis}</small></div>`).join('')}</section>
    <p class="market-small market-overview-note">Mkt Cap uses outstanding Solana KPEPE supply and the displayed price. Liquidity is Raydium’s reported USD TVL.</p>
    <section class="market-statistics" aria-label="Market statistics">${[['current','Displayed price · see source'],['change','24h change'],['volume','24h volume · SOL'],['high','24h high · SOL'],['low','24h low · SOL'],['count','24h trades']].map(([id,label])=>`<div class="market-card market-stat"><span>${label}</span><strong data-market="stat-${id}">—</strong></div>`).join('')}</section>
    <p class="market-small market-coverage" data-market="coverage">24h statistics require complete verified coverage.</p>
    </div>
    <section class="market-card market-trades" aria-labelledby="market-trades-title"><div class="market-section-head"><div><h2 id="market-trades-title">Live trades</h2><p class="market-small">Finalized Raydium swaps · newest first</p></div><span class="market-tag">DISPLAY ONLY</span></div><div class="market-table-wrap"><table><caption class="market-sr-only">Verified KPEPE market trades. Buy means KPEPE acquired; sell means KPEPE disposed.</caption><thead><tr><th scope="col">Side</th><th scope="col">KPEPE amount</th><th scope="col">SOL value</th><th scope="col">Price · SOL</th><th scope="col">Time</th></tr></thead><tbody data-market="trades"><tr><td colspan="5" class="market-table-empty">No verified trade history available.</td></tr></tbody></table></div><p class="market-small" data-market="trade-note">Quotes, pending transactions and failed transactions are excluded.</p></section>
    </div>
    <section aria-labelledby="market-venues-title"><div class="market-section-head market-venues-title"><h2 id="market-venues-title">Raydium market</h2><span class="market-small">KPEPE / SOL · Display only</span></div><div class="market-venues">
      <article class="market-card market-venue market-venue-raydium"><div class="market-pool-summary"><div class="market-section-head"><h3><span class="venue-mark ray">R</span> Raydium CLMM</h3><span class="market-tag" data-market="ray-status">—</span></div><a class="market-address" href="${explorer('address',MARKET.raydium)}" target="_blank" rel="noopener noreferrer" aria-label="View Raydium pool on Solana Explorer">Pool ${short(MARKET.raydium)} ↗</a><dl>${[['ray-reference','Pool reference · SOL'],['ray-vaults','Pool vault balances'],['ray-tvl','Provider TVL estimate · USD'],['ray-volume','Provider 24h volume · USD']].map(([k,t])=>`<div><dt>${t}</dt><dd data-market="${k}">—</dd></div>`).join('')}</dl>
        <div class="market-explanation"><h4>Reading this market</h4><p>The pool reference is a marginal price, not an executable quote. Vault balances include inventory and fees; they are not available buy depth.</p><p>TVL and volume are Raydium provider estimates. Unknown values appear as —.</p></div></div><div class="market-order"><h4>Original Native Limit order</h4><a class="market-address" href="${explorer('address',MARKET.order)}" target="_blank" rel="noopener noreferrer" aria-label="View original Native Limit order on Solana Explorer">${short(MARKET.order)} ↗</a><dl>${[['order-status','Status'],['order-ask','Order ask · SOL / KPEPE'],['order-initial','Initial inventory · KPEPE'],['order-remaining','Remaining · KPEPE'],['order-filled','Filled · KPEPE'],['order-claimable','Claimable · WSOL'],['order-settled','Settled this segment · WSOL']].map(([k,t])=>`<div><dt>${t}</dt><dd data-market="${k}">—</dd></div>`).join('')}</dl><p class="market-small">This card follows the original order only. Pool vault balances may also include other orders and fees.</p></div></article>
    </div></section>
    <section class="market-card market-methodology"><details><summary>Data sources &amp; freshness</summary><p>Finalized Solana accounts verify this exact Raydium pool, the official Mint and the original Raydium order. Trades are decoded from successful Raydium swap events; known Team participants are excluded. Public data cannot prove beneficial ownership.</p><p>Price preference: latest verified finalized trade, then a verified executable quote when available, then the tracked active ask, then a labeled pool reference. A last trade can be old; its time is always shown. This display currently has no verified executable quote source.</p><p>Accounts refresh every 30 seconds; history and venue estimates every 60 seconds. LIVE requires accounts within 90 seconds and history scans within 3 minutes. Old values are marked stale and removed after 5 minutes. Chart history is bounded to 7 days / 500 displayed swaps, with no interpolation.</p><p>USD conversion, when fresh, uses Coinbase SOL/USD. TVL and venue USD volume are provider estimates from Raydium. 24h change compares the first and last verified trades inside the window; incomplete coverage shows —.</p><p>Mkt Cap is an indicative valuation of outstanding Solana Mint supply at the displayed price. Native supply and FDV are not included. A resting-ask valuation is not a verified circulating market cap. Reported Raydium TVL may exclude unpriced assets or Native Limit inventory and is not executable buying depth.</p><p>Market-data health is independent of Bridge availability. No market wallet connection or transactions are available here.</p></details></section>
    <footer class="market-data-footer"><span data-market="updated">Waiting for market data</span><a href="${explorer('address',MARKET.mint)}" target="_blank" rel="noopener noreferrer">Official KPEPE Mint ↗</a></footer>`;
  host.replaceChildren(root);
  const $=key=>root.querySelector(`[data-market="${key}"]`);let data=null,frame='ALL',stopped=false,timer,healthTimer,controller;
  const text=(key,value)=>{$(key).textContent=value;};
  const when=at=>Number.isFinite(at)?new Date(at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
  const unit=(n,s,d=8)=>f(n,d)==='—'?'—':f(n,d)+' '+s;
  function drawChart(){
    const trades=data?.trades??[],series=chartSeries(trades,frame);
    for(const button of root.querySelectorAll('[data-frame]')){button.disabled=chartSeries(trades,button.dataset.frame).type==='EMPTY';button.setAttribute('aria-pressed',String(button.dataset.frame===frame));}
    const container=$('chart');container.replaceChildren();
    if(series.type==='EMPTY'){const e=document.createElement('div');e.className='market-empty';const strong=document.createElement('strong'),p=document.createElement('p');strong.textContent='Insufficient trading history';p.textContent='Only verified, finalized trades appear here.';e.append(strong,p);container.append(e);text('chart-summary','No synthetic candles, prices or volume.');return;}
    const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 780 310');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${series.type==='CANDLES'?'OHLC candles':'Trade-price line'} from ${series.points.length} finalized pool swaps, prices in SOL per KPEPE.`);
    const element=(tag,attrs,label)=>{const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(label)e.textContent=label;svg.append(e);return e;};
    const points=series.points,minTime=points[0].timestamp,maxTime=points.at(-1).timestamp,prices=points.map(p=>p.priceSol),min=Math.min(...prices),max=Math.max(...prices),pad=Math.max((max-min)*.12,max*.001),low=min-pad,high=max+pad;
    const x=t=>14+(t-minTime)/(maxTime-minTime)*650,y=p=>270-(p-low)/(high-low)*245;
    for(let i=0;i<5;i++){const yy=25+i*61.25;element('line',{x1:14,y1:yy,x2:664,y2:yy,class:'market-grid-line'});element('text',{x:678,y:yy+4,class:'market-axis'},f(high-i*(high-low)/4,6));}
    if(series.type==='LINE')element('polyline',{points:points.map(p=>x(p.timestamp)+','+y(p.priceSol)).join(' '),class:'market-line'});
    else for(const c of series.candles){const xx=Math.max(14,Math.min(664,x(c.time))),up=c.close>=c.open,cls=up?'market-candle-up':'market-candle-down';element('line',{x1:xx,y1:y(c.high),x2:xx,y2:y(c.low),class:cls});element('rect',{x:xx-3,y:Math.min(y(c.open),y(c.close)),width:6,height:Math.max(1,Math.abs(y(c.open)-y(c.close))),class:cls});}
    element('text',{x:14,y:301,class:'market-axis'},when(minTime));element('text',{x:664,y:301,'text-anchor':'end',class:'market-axis'},when(maxTime));container.append(svg);
    text('chart-summary',`${points.length} finalized pool swaps · ${series.type==='CANDLES'?'OHLC from nonempty trade intervals':'Line connects actual trades; gaps are not activity'} · low ${f(min,8)} / high ${f(max,8)} SOL`);
  }
  function paint(){
    const health=displayHealth(data);text('health',health==='PARTIAL'?'PARTIAL DATA':health==='UNAVAILABLE'?'UNAVAILABLE':health);root.querySelector('.market-health').dataset.health=health;
    const d=health==='UNAVAILABLE'?null:data,p=d?.priceSol;
    const overview=overviewMetrics(d),dollars=(value,digits=2)=>value===null?'—':'≈ $'+f(value,digits);
    text('overview-cap',dollars(overview.marketCapUsd));text('overview-liquidity',dollars(overview.liquidityUsd));text('overview-usd',dollars(overview.priceUsd,4));
    text('price-label',PRICE_LABELS[d?.priceType]??PRICE_LABELS.UNAVAILABLE);text('price',f(p,9));text('usd',overview.priceUsd!==null?dollars(overview.priceUsd,4):'$ —');text('price-time',when(d?.priceAt));
    text('price-context',health==='STALE'?'Stale snapshot · reconnecting':d?.priceType==='LAST_FINALIZED_TRADE'?'Historical execution, not a live quote':d?.priceType==='TRACKED_ORDER_ASK'?'Original resting order, not a last trade':d?'Marginal pool reference':'Market data temporarily unavailable');
    const s=d?.history?.observedAt&&Date.now()-d.history.observedAt<=FRESHNESS.historyMs?d.stats24h:{};text('stat-current',unit(p,'SOL',9));text('stat-change',s.changePct===null||s.changePct===undefined?'—':f(s.changePct,2)+'%');text('stat-volume',f(s.volumeSol,6));text('stat-high',f(s.highSol,9));text('stat-low',f(s.lowSol,9));text('stat-count',f(s.tradeCount,0));
    text('coverage',d?.history?.complete24h?'24h totals cover verified Raydium pool swaps. Change is first-to-last within that window.':'Partial history coverage · 24h aggregates withheld until verified.');
    const body=$('trades');body.replaceChildren();
    for(const t of (d?.trades??[]).slice(0,20)){const row=document.createElement('tr');const side=document.createElement('td');side.textContent=t.side;side.className=t.side==='BUY'?'market-buy-history':'market-sell-history';row.append(side);
      for(const value of [f(t.kpepe,8),f(t.sol,9),f(t.priceSol,9)]){const td=document.createElement('td');td.textContent=value;row.append(td);}
      const td=document.createElement('td'),a=document.createElement('a');a.href=explorer('tx',t.signature);a.target='_blank';a.rel='noopener noreferrer';a.textContent=when(t.timestamp)+' ↗';a.title=t.venue+' · '+t.signature;a.setAttribute('aria-label','View finalized '+t.venue+' swap at '+when(t.timestamp));td.append(a);row.append(td);body.append(row);}
    if(!body.children.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.className='market-table-empty';td.textContent=d?.history?.complete24h&&d?.history?.health==='FRESH'?'No finalized trades in the verified history window.':'No verified trade history available.';row.append(td);body.append(row);}
    text('trade-note',d?.history?.health==='FRESH'?'BUY / SELL describe each pool swap from the trader’s perspective. Links open public transaction evidence.':'Trade feed temporarily unavailable. Any retained rows are previously finalized history.');
    const r=d?.raydium,order=r?.order,stats=d?.statistics&&Date.now()-d.statistics.observedAt<=FRESHNESS.statisticsMs?d.statistics:null;
    const readable=s=>s?s.replaceAll('_',' ')+(health==='STALE'?' · STALE':''):'UNAVAILABLE';text('ray-status',readable(r?.status));
    text('ray-reference',f(r?.referencePriceSol,9));text('ray-vaults',r?f(r.vaultKpepe,8)+' KPEPE + '+f(r.vaultSol,9)+' SOL':'—');text('ray-tvl',f(stats?.raydium?.tvlUsd,2));text('ray-volume',f(stats?.raydium?.volume24hUsd,2));
    text('order-status',readable(order?.status));text('order-ask',f(order?.askSol,9));text('order-initial',f(order?.initialKpepe,8));text('order-remaining',f(order?.remainingKpepe,8));text('order-filled',f(order?.filledKpepe,8));text('order-claimable',f(order?.claimableWsol,9));text('order-settled',f(order?.settledWsol,9));
    text('updated',d?`${health==='STALE'?'Last verified':'Accounts verified'} ${when(d.observedAt)} · finalized slot ${d.slot}`:'Market data temporarily unavailable. Bridge readiness is checked separately.');
    if(d)drawChart();else{const old=data;data=null;drawChart();data=old;}
  }
  for(const button of root.querySelectorAll('[data-frame]'))button.onclick=()=>{frame=button.dataset.frame;drawChart();};
  async function refresh(){if(stopped)return;controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);
    try{const response=await fetch('/api/v1/market/live',{method:'GET',credentials:'omit',redirect:'error',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('UNAVAILABLE');const next=validateMarket(await response.json());if(!stopped)data=next;}catch{}finally{clearTimeout(timeout);if(!stopped){paint();timer=setTimeout(refresh,data?.observedAt?30000:8000);}}}
  void refresh();healthTimer=setInterval(paint,10000);
  return ()=>{stopped=true;clearTimeout(timer);clearInterval(healthTimer);controller?.abort();};
}
