[package]
name = "kingpepe-transceiver"
version = "0.1.0"
edition = "2021"
publish = false
license-file = "../../../LICENSE"

[lib]
name = "kingpepe_transceiver"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
bridge-messages = { path = "../../modules/bridge-messages" }
solana-program = "=3.0.0"
solana-system-interface = { version = "=2.0.0", features = ["bincode"] }
thiserror = "1.0.69"

[dev-dependencies]
solana-instructions-sysvar = "=3.0.1"
